### ISSUE TITLE
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib

### ISSUE THREAD

**Issue by kiiiooo** [bytedeco/sample-projects#72] opened 2024-11-07 10:10 UTC
Hi, I use `javacpp:1.5.10` and `ffmpeg-platform:6.1.1-1.5.10` in my Spring Boot project. When I run the application in my local computer, it works fine. However in the docker container , the `UnsatisfiedLinkError` was thrown. I confirm that  my jar file contains dependencies of all platform, but javacpp seems not found them and load them correctlly.

the `build.gradle.kts` file:
```kotlin
    // ffmpeg
    implementation("org.bytedeco:javacpp:1.5.10")
    implementation("org.bytedeco:ffmpeg-platform:6.1.1-1.5.10")
```

packaged jar file:

![image](https://github.com/user-attachments/assets/bc3741d1-8db7-41a1-9861-5e8e46bdc605)

the full error stack:

```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib [in thread "pool-6-thread-6"]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:2006)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
        at org.bytedeco.ffmpeg.global.avutil.<clinit>(avutil.java:14)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
        at org.bytedeco.ffmpeg.avformat.AVFormatContext.<clinit>(AVFormatContext.java:36)
        ... 7 common frames omitted

```

**Comment by saudet** [comment] 2024-11-07 10:56
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1379

**Closed as completed by saudet** 2024-11-07 10:56 UTC
Labels: duplicate, enhancement
