### ISSUE TITLE
how to gracefully close video stream chunker operation in middle of execution (referring to streaming-chunker sample example)

### ISSUE THREAD

**Issue by gowridev** [bytedeco/sample-projects#34] opened 2018-06-13 12:56 UTC
@d-a-gerashenko 
I am running streaming video in one thread and recording in another. when i close the streaming event. i would like to close the recording event as well. how to do i  gracefully close video stream chunker operation in middle of execution (referring to streaming-chunker sample example). I am unable to call "fFmpegChunker.stop();" in time so video file not getting closed properly. Could you please guide me? 

P.S.: this logic is working fine for live streaming

**Comment by saudet** [comment] 2018-06-14 01:12
Duplicate of https://github.com/bytedeco/javacv/issues/991

Until this is fixed somehow, you could use synchronized blocks.

**Closed by saudet** 2018-06-14 01:13 UTC

**Comment by d-a-gerashenko** [comment] 2018-06-14 01:29
StreamingChunker designed to grab from infinite stream. If you stop video stream on a middle of chunk the chunk will not be finalized.

**Comment by d-a-gerashenko** [comment] 2018-06-14 02:01
First of all this demo code is not thread safe so you shouldn't invoke start/stop from multiple threads. 
Instead you should use some synchronized wrapper. For example:

	@Override
    public void run() {
        try {
            chunker.start();
            while (!isStoping()) {
                if (!chunker.next()) {
                    throw new RuntimeException("Chunker returned NULL.");
                }
            }
        } catch (Exception e) {
            throw new RuntimeException("Stopped on error.", e);
        } finally {
            try {
                chunker.stop();
            } catch (Exception e) {
				throw new RuntimeException("Can't stop chunker.", e);
            }
        }

    }


I see only one way to produce a corrupted chunk when there are no enough frames but you will not be notified (fFmpegChunker.setChunkHandler) about this chunk because it's a temp unfinished file.

Are you sure that the corrupted file is not the last temp file? Does Chunker notified you about it's finished chunk?

Or it could be a bug that was written about.
