### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by RamanKreiza** [bytedeco/sample-projects#13] opened 2017-04-23 20:17 UTC
Hello I am trying to run https://github.com/bytedeco/sample-projects/tree/master/caffe-sample-classifier on my pc(windows 10 x64) and i take this errors:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnicaffe in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
        at org.bytedeco.javacpp.Loader.load(Loader.java:613)
        at org.bytedeco.javacpp.Loader.load(Loader.java:530)
        at org.bytedeco.javacpp.caffe.<clinit>(caffe.java:17)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.bytedeco.javacpp.Loader.load(Loader.java:585)
        at org.bytedeco.javacpp.Loader.load(Loader.java:530)
        at org.bytedeco.javacpp.caffe$Caffe.<clinit>(caffe.java:3926)
        at org.bytedeco.javacpp.caffe_example.Main.main(Main.java:23)
Caused by: java.lang.UnsatisfiedLinkError: no openblas in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
        at org.bytedeco.javacpp.Loader.load(Loader.java:604)
        ... 8 more

```
My run string: java -jar caffe-sample-classifier-all.jar deploy.prototxt bvlc_reference_caffenet.caffemodel imagenet_mean.binaryproto synset_words.txt cat.jpg

I am look at the caffe-sample-classifier-all.jar and it does not contain jnicaffe.so and openblas.so only libopencv<some name>.so libs

And one more problem maybe not on the topic. When I start gradle.bat for the second time in another directory, it can not create a caffe-sample-classifier-all.jar but creates caffe-sample-classifier.jar without libraries. gradlew build cant help too.

Could you help with these errors?

**Comment by saudet** [comment] 2017-04-24 01:01
This is normal, there are no binaries for Windows yet.

Marking as duplicate of issue bytedeco/javacpp-presets#34

**Closed by saudet** 2017-04-24 01:01 UTC
Labels: duplicate, enhancement
