### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: no jnicaffe in java.library.path

### ISSUE THREAD

**Issue by OleksandrGrument** [bytedeco/sample-projects#27] opened 2018-04-07 12:35 UTC
Hi, I download a sample project and have this exception, how to solve this problem or what is a possible reason that cause this problem? I did not found any working solution. My OS is Windows 10. Thanks.

`Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnicaffe in java.library.path
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2541)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:873)
	at java.base/java.lang.System.loadLibrary(System.java:1857)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:777)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.bytedeco.javacpp.caffe.<clinit>(caffe.java:17)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.bytedeco.javacpp.Loader.load(Loader.java:739)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.bytedeco.javacpp.caffe$Caffe.<clinit>(caffe.java:3926)
	at org.bytedeco.javacpp.caffe_example.Main.main(Main.java:44)
Caused by: java.lang.UnsatisfiedLinkError: no openblas in java.library.path
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2541)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:873)
	at java.base/java.lang.System.loadLibrary(System.java:1857)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:765)
	... 8 more

Process finished with exit code 1`

**Comment by saudet** [comment] 2018-04-07 14:34
Windows is not currently supported. Marking as duplicate of #34.

**Closed by saudet** 2018-04-07 14:34 UTC
Labels: duplicate, enhancement

**Comment by OleksandrGrument** [comment] 2018-04-08 09:51
Well, I installed Ubuntu 17.04 and Caffe and have the same issue

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnicaffe in java.library.path

Maybe is some solution ? Thanks

**Comment by OleksandrGrument** [comment] 2018-04-08 10:16
Found solution, i have version 1.3 i updated on 1.4 and it works. Thanks
